import os

# Known Data
DATA_FOLDER = '/home/jineshmehta/new-jobs-notifier/data'
COMPANY_NAMES_CSV = os.path.join(DATA_FOLDER, 'company_data.csv')
COMPANY_SEARCH_API_CSV = os.path.join(DATA_FOLDER, 'search_api.csv')
COMPANY_KEYWORDS_CSV = os.path.join(DATA_FOLDER, 'keywords.csv')
COMPANY_KNOWN_JOBS_CSV = os.path.join(DATA_FOLDER, 'already_known_jobs.csv')
COMPANY_SEARCH_API_HEADER_CSV = os.path.join(DATA_FOLDER, 'search_headers.csv')

# Log File Location
LOG_FILE_LOCATION = "log/log.log"
SLACK_DEPLOYMENT_NOTIFICATION_WEBHOOK_VAR = 'SLACK_DEPLOYMENT_NOTIFICATION_WEBHOOK'
SLACK_ERROR_NOTIFICATION_WEBHOOK_VAR = 'SLACK_ERROR_NOTIFICATION_WEBHOOK'
SLACK_JOB_NOTIFICATION_WEBHOOK_VAR = 'SLACK_JOB_NOTIFICATION_WEBHOOK'
